services:
  web:
    container_name: mylibsqladmin-web
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        APP_ENV: development
        ENV_FILE: .env.local # Use the development env file
    ports:
      - "8000:8000" # Laravel
      - "9003:9003" # Xdebug
      - "5173:5173" # Vite
    volumes:
      - ./admin:/var/www/html
      - ./admin/storage:/var/www/html/storage
    env_file: "./.env" # Root env file (can hold overrides for dev)
    networks:
      - app-network
    restart: always
    profiles: ["development"]

  web_prod:
    container_name: mylibsqladmin-web
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        APP_ENV: production
        ENV_FILE: .env.production # Use the production env file
    ports:
      - "8000:8000"
    volumes:
      - ./admin/database:/var/www/html/database
    env_file: "./.env" # Root env file (can hold overrides for dev)
    networks:
      - app-network
    restart: always
    profiles: ["production"]

  proxy:
    container_name: mylibsqladmin-proxy
    image: openresty/openresty:alpine
    ports:
      - "8080:8080"
      - "5001:5001"
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    restart: always
    depends_on:
      db:
        condition: service_started
    profiles: ["local-instance"]

  db:
    container_name: mylibsqladmin-db
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    entrypoint: ["/bin/sqld"]
    command:
      - "--http-listen-addr"
      - "0.0.0.0:8080"
      - "--grpc-listen-addr"
      - "0.0.0.0:5001"
      - "--admin-listen-addr"
      - "0.0.0.0:8081"
      - "--enable-namespaces"
      - "--no-welcome"
    user: "1000:1000"
    volumes:
      - ./data:/var/lib/sqld
    restart: always
    networks:
      - app-network
    profiles: ["local-instance"]

networks:
  app-network:
    driver: bridge
