services:
  web:
    container_name: mylibsqladmin-webui-dev
    build:
      context: ./webapp
      dockerfile: Dockerfile.local
      args:
        APP_ENV: development
        ENV_FILE: .env.local # Use the development env file
    ports:
      - '8000:8000' # Laravel
      - '9003:9003' # Xdebug
      - '5173:5173' # Vite
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - app-network
    restart: always
    profiles: ['development']

  web_prod:
    container_name: mylibsqladmin-webui-prod
    build:
      context: ./webapp
      dockerfile: Dockerfile.production
      args:
        APP_ENV: production
        APP_DEBUG: false
        ENV_FILE: .env.production # Use the production env file
    ports:
      - '8000:8000'
    networks:
      - app-network
    restart: unless-stopped
    profiles: ['production']

  proxy:
    container_name: mylibsqladmin-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '5001:5001'
      - '8081:8081'
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
    profiles: ['local-instance']

  db:
    container_name: mylibsqladmin-db
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    entrypoint: ['/bin/sqld']
    command:
      - '--http-listen-addr'
      - '0.0.0.0:8080'
      - '--grpc-listen-addr'
      - '0.0.0.0:5001'
      - '--admin-listen-addr'
      - '0.0.0.0:8081'
      - '--enable-namespaces'
      - '--no-welcome'
    user: '1000:1000'
    volumes:
      - ./libsql-data:/var/lib/sqld
    restart: unless-stopped
    networks:
      - app-network
    profiles: ['local-instance']

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - app-network
    profiles: ['development']

networks:
  app-network:
    driver: bridge
