name: Publish Development Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Development Images
        run: make compose-dev/build

      - name: Build and Push Development Local Instance Images
        run: make compose-dev-lli/build

      - name: Build and Push Development Remote Instance Images
        run: make compose-dev-lri/build
